version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: halosemua
    volumes:
      - ./seeds-test:/docker-entrypoint-initdb.d
