version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - ${POSTGRESQL_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      - ${SEED_FOLDER}:/docker-entrypoint-initdb.d
