version: '3.1'

services:
  organizations-api:
    container_name: organizations-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
        - "8123:8012"
  postgres:
    image: postgres
    restart: always
    ports:
      - ${POSTGRESQL_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      - ${SEED_FOLDER}:/docker-entrypoint-initdb.d
